# Pods are meant to be "ephemeral", and are supposed to just be throw-aways.
# The analogy of treating them like cattle is often used.
### Old Pod:
# apiVersion: v1
# kind: Pod
# metadata:
#     name: webapp
#     labels: # can be any key value pairs
#         app: webapp
#         release: "0"
# spec:
#     containers:
#         - name: webapp
#           image: richardchesterwood/k8s-fleetman-webapp-angular:release0

# ---
# apiVersion: apps/v1
# # kind: Pod
# kind: ReplicaSet
# metadata:
#     name: webapp # can be anything, but common to use same name as pod template
# spec:
#     selector:
#       matchLabels:
#         app: webapp
#     replicas: 2
#     template: # pod template
#         ### Below is the same info used for the old pod
#         metadata:
#             # name: webapp ### name is no longer needed
#             labels:
#                 app: webapp
#         spec:
#             containers:
#                 - name: webapp
#                   image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: apps/v1
# kind: Pod
kind: Deployment
metadata:
    name: webapp # can be anything, but common to use same name as pod template
spec:
    # minReadySeconds: 30
    selector:
      matchLabels:
        app: webapp
    replicas: 2
    template: # pod template
        ### Below is the same info used for the old pod
        metadata:
            # name: webapp ### name is no longer needed
            labels:
                app: webapp
        spec:
            containers:
                - name: webapp
                  image: richardchesterwood/k8s-fleetman-webapp-angular:release0


---
apiVersion: v1
kind: Pod
metadata:
    name: queue
    labels: # can be any key value pairs
        app: queue
spec:
    containers:
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release1
