apiVersion: v1
kind: PersistentVolumeClaim # What do we want with the volume
metadata:
    name: mongo-pvc
spec:
    # storageClassName: mylocalstorage # used to bind with pers vol
    storageClassName: cloud-ssd
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi

# ---
# apiVersion: v1
# kind: PersistentVolume # How are we going to implement volume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: mylocalstorage # used to bind with pvc
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/mongodb-2
#     type: DirectoryOrCreate

# Added to debug elk
####################
---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: local-storage
spec:
  storageClassName: localstorage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate
####################
# End debug

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
    type: gp2
